service igc
{
	type net;
	descr "Intel I225/I226 2.5G Ethernet";
        system
                UMAP            # 14
                IRQCTL          # 19
                DEVIO           # 21
        ;
        /* I225 */
        pci device      8086:15f2;      /* I225-LM */
        pci device      8086:15f3;      /* I225-V  */
        pci device      8086:15f8;      /* I225-I  */
        pci device      8086:0d9f;      /* I225-IT */
        pci device      8086:15fd;      /* I225 blank NVM */
        /* I226 */
        pci device      8086:125b;      /* I226-LM   */
        pci device      8086:125c;      /* I226-V    */
        pci device      8086:125d;      /* I226-IT   */
        pci device      8086:5502;      /* I226-K    */
        pci device      8086:5503;      /* I226-LMVP */
        ipc
                SYSTEM pm rs log tty ds vm
                pci inet lwip ;
};
