#!/bin/sh
#
# $NetBSD: syslogd,v 1.15 2004/10/11 13:29:52 lukem Exp $
#

# PROVIDE: syslogd
# REQUIRE: mountcritremote sysdb wscons
# BEFORE:  SERVERS

$_rc_subr_loaded . /etc/rc.subr

name="syslogd"
rcvar=$name
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/syslog.conf"
start_precmd="syslogd_precmd"
extra_commands="reload"

_sockfile="/var/run/syslogd.sockets"

syslogd_precmd()
{
	#	syslogd bind(2)s its datagram log socket(s) under /var/run
	#	(/var/run/log and any chroot sockets below).  On a freshly
	#	created /var ramdisk that directory can be absent, in which
	#	case the bind fails with "Cannot create `/var/run/log'" and
	#	syslogd dies.  Make sure it exists before we start.
	mkdir -p /var/run

	#	syslogd opens its log files with O_WRONLY|O_APPEND but does
	#	NOT pass O_CREAT.  On a CD/ramdisk boot /var/log is symlinked
	#	to a freshly-created /tmp/log (see /usr/etc/rc), so the log
	#	files don't exist yet and syslogd reports
	#	  "/var/log/syslog: No such file or directory"
	#	for each entry in /etc/syslog.conf.  Pre-create them here so
	#	the first messages have somewhere to land.  Use install(1)
	#	with mode 600 to match syslogd's expected ownership/perms;
	#	fall back silently if the destination is read-only.
	mkdir -p /var/log 2>/dev/null || :
	for _f in /var/log/syslog /var/log/messages; do
		[ -e "$_f" ] || install -c -m 600 /dev/null "$_f" 2>/dev/null || :
	done
	unset _f

	#	Transitional symlink for old binaries
	#
	# MINIX 3: unsupported, disabled
	#if [ ! -h /dev/log ]; then
	#	ln -sf /var/run/log /dev/log
	#fi
	# MINIX 3: end

	#	Create default list of syslog sockets to watch
	#
	( umask 022 ; > $_sockfile )

	#	Find /etc/rc.d scripts with "chrootdir" rcorder(8) keyword,
	#	and if $${app}_chrootdir is a directory, add appropriate
	#	syslog socket to list of sockets to watch.
	#
	for _lr in $(rcorder -k chrootdir /etc/rc.d/*); do
	    (
		_l=${_lr##*/}
		load_rc_config ${_l}
		eval _ldir=\$${_l}_chrootdir
		if checkyesno $_l && [ -n "$_ldir" ]; then
			echo "${_ldir}/var/run/log" >> $_sockfile
		fi
	    )
	done

	#	If other sockets have been provided, change run_rc_command()'s
	#	internal copy of $syslogd_flags to force use of specific
	#	syslogd sockets.
	#
	if [ -s $_sockfile ]; then
		echo "/var/run/log" >> $_sockfile
		rc_flags="-P $_sockfile $rc_flags"
	fi

	return 0
}

load_rc_config $name
run_rc_command "$1"
