#	MINIX 3: build llvm-nm as a host tool, to replace binutils' nm.

HOSTPROGNAME=	${MACHINE_GNU_PLATFORM}-nm
HOSTPROG_CXX=	${MACHINE_GNU_PLATFORM}-nm
HOST_SRCDIR=	external/apache2/llvm/bin/llvm-nm

.include "${.CURDIR}/../Makefile.host"
