#	Minix amd64 machine-level include install

INCSDIR= /usr/include/amd64

INCS=	ansi.h asm.h aout_machdep.h bswap.h byte_swap.h \
	cdefs.h \
	coff_machdep.h cpu.h cpufunc.h float.h \
	kcore.h \
	db_machdep.h disklabel.h \
	ecoff_machdep.h elf_machdep.h \
	endian.h endian_machdep.h \
	fenv.h frame.h \
	hash.h \
	ieee.h ieeefp.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	interrupt.h intrdefs.h intr.h \
	limits.h lock.h \
	math.h mcontext.h multiboot.h mutex.h \
	param.h pcb.h pic.h pmap.h pmc.h proc.h profile.h psl.h pte.h ptrace.h \
	rwlock.h \
	segments.h setjmp.h signal.h \
	trap.h tss.h types.h \
	varargs.h vmparam.h \
	wchar_limits.h

.include <bsd.kinc.mk>
