.include <bsd.own.mk>

.if ${MACHINE_ARCH} == "i386" || ${MACHINE_ARCH} == "x86_64"
SUBDIR+=	als4000
SUBDIR+=	cmi8738
SUBDIR+=	cs4281
SUBDIR+=	es1370
SUBDIR+=	es1371
SUBDIR+=	sb16
SUBDIR+=	trident
.endif # i386 || x86_64

.include <bsd.subdir.mk>
