# $NetBSD: Makefile,v 1.3 2019/06/14 01:54:16 christos Exp $

.include <bsd.own.mk>

FILES=		postinstall
MAN=		postinstall.8

FILESDIR=	/usr/sbin
FILESMODE=	${BINMODE}

# The postinstall script is pre-built (not generated) for MINIX
# since the tool chain may not be fully available

.include <bsd.prog.mk>
