#	MINIX 3: build ld.lld as a host tool, so the cross toolchain can use it
#	as the target linker.

HOSTPROGNAME=	${MACHINE_GNU_PLATFORM}-ld.lld
HOSTPROG_CXX=	${MACHINE_GNU_PLATFORM}-ld.lld
HOST_SRCDIR=	external/apache2/llvm/bin/lld

.include "${.CURDIR}/../Makefile.host"
