service usbd
{
	system
			PRIVCTL 
			UMAP
			IRQCTL
			;
	irq
			92 #BeagleXM
			17 #BeagleBoneWhite
			18 #BeagleBoneWhite
			19 #BeagleBoneWhite
			16 #EHCI amd64 (PCI IRQ, APIC GSI base)
			17 #EHCI amd64
			18 #EHCI amd64
			19 #EHCI amd64
			20 #EHCI amd64
			21 #EHCI amd64
			22 #EHCI amd64
			23 #EHCI amd64
			;
};
