service usbd
{
	system
			PRIVCTL
			UMAP
			IRQCTL
			;
	ipc
			SYSTEM pm rs log tty ds vfs vm amddev devman
			pci
			;
	irq
			92	#BeagleXM
			9	#amd64 PCI
			10	#amd64 PCI
			11	#amd64 PCI
			12	#amd64 PCI
			16	#amd64 PCI (APIC GSI)
			17	#amd64 PCI
			18	#amd64 PCI
			19	#amd64 PCI
			20	#amd64 PCI
			21	#amd64 PCI
			22	#amd64 PCI
			23	#amd64 PCI
			;
	uid	0;
};
